\chapter{Catching Exceptions\label{chap:CatchingExceptions}}

Exception catchers are grammatically derived from $\Ncatcher$ and represented as ASTs by $\catcher$.

\hypertarget{def-annotatecatcher}{}
The function
\[
\begin{array}{r}
  \annotatecatcher{
    \overname{\staticenvs}{\tenv} \aslsep
    \overname{\TSideEffectSet}{\vsesin} \aslsep
    \overname{\catcher}{\vc}
  } \aslto \\
  (\overname{\TSideEffectSet}{\vsesfiltered} \times (\overname{\catcher}{\newcatcher}, \overname{\TSideEffectSet}{\vses}))
  \cup \overname{\TTypeError}{\TypeErrorConfig}
\end{array}
\]
annotates a catcher $\vc$ in the static environment $\tenv$
and \sideeffectsetterm\ $\vsesin$.
The result is the \sideeffectsetterm\ $\vsesfiltered$, the annotated catcher $\newcatcher$ and the
\sideeffectsetterm\ $\vses$.
\ProseOtherwiseTypeError

The semantic relation for evaluating catchers employs an argument
that is an output configuration. This argument corresponds to the result
of evaluating a \texttt{try} statement and its type is defined as follows:
\hypertarget{def-toutconfig}{}
\[
  \TOutConfig \triangleq \TNormal \cup  \TThrowing \cup \TContinuing \cup \TReturning \enspace.
\]

The relation
\hypertarget{def-evalcatchers}{}
\[
  \evalcatchers{\overname{\envs}{\env} \aslsep \overname{\catcher^*}{\catchers} \aslsep \overname{\langle\stmt\rangle}{\otherwiseopt}
   \aslsep \overname{\TOutConfig}{\sm}} \;\aslrel\;
  \left(
    \begin{array}{cl}
      \TReturning   & \cup\\
      \TContinuing  & \cup\\
      \TThrowing    & \cup \\
      \TDynError       &
    \end{array}
  \right)
\]
evaluates a list of \texttt{catch} clauses $\catchers$, an \texttt{otherwise} clause,
and a configuration $\sm$ resulting from the evaluation of the throwing expression,
in the environment $\env$. The result is either a continuation configuration,
an early return configuration, or an abnormal configuration.

When the statement in a \texttt{try} block, which we will refer to as the try-block statement,
is evaluated, it may call a function that updates
the global environment. If evaluation of the \texttt{try} block raises an exception that is caught,
either by a \texttt{catch} clause or an \texttt{otherwise} clause,
the statement associated with that clause, which we will refer to as the clause statement, is evaluated.
It is important to evaluate the clause statement in an environment that includes any updates
to the global environment made by evaluating the try-block statement.
%
We demonstrate this with the following example.

\ASLListing{Semantics of exception catching}{semantics-evalcatchers}{\semanticstests/EvalCatchers.asl}

In \listingref{semantics-evalcatchers}, the statement \verb|update_and_throw();|
makes up the whole try-block.
Evaluating the call to \verb|update_and_throw| employs an environment $\env$ where
\texttt{g} is bound to $0$.
Notice that the call to \verb|update_and_throw| binds \texttt{g} to $1$ before raising an exception.
Therefore, evaluating the call to \verb|update_and_throw| returns a configuration
of the form
$\Throwing(\Ignore, \envthrow)$ where $\envthrow$ binds \texttt{g} to $1$.
When the catch clause is evaluated the semantics takes the global environment from $\envthrow$
to account for the update to \texttt{g} and the local environment from $\env$ to account for the
updates to the local environment in \texttt{main}, which binds \texttt{x} to $2$, and use this
environment to evaluate \texttt{print(x, g)}, resulting in the output \texttt{2 1}.

\section{Syntax}
\begin{flalign*}
\Ncatcher \derives      \ & \Twhen \parsesep \Tidentifier \parsesep \Tcolon \parsesep \Nty \parsesep \Tarrow \parsesep \Nstmtlist &\\
          |\              & \Twhen \parsesep \Nty \parsesep \Tarrow \parsesep \Nstmtlist &\\
\end{flalign*}

\section{Abstract Syntax}
\begin{flalign*}
\catcher \derives\ & (\overtext{\identifier?}{exception to match}, \overtext{\ty}{guard type}, \overtext{\stmt}{statement to execute on match}) &
\end{flalign*}

\ASTRuleDef{Catcher}
\hypertarget{build-catcher}{}
The function
\[
\buildcatcher(\overname{\parsenode{\Ncatcher}}{\vparsednode}) \;\aslto\; \overname{\catcher}{\vastnode}
\]
transforms a parse node $\vparsednode$ into an AST node $\vastnode$.

\begin{mathpar}
\inferrule[named]{}{
  {
  \begin{array}{r}
  \buildcatcher(\overname{\Ncatcher(\Twhen, \Tidentifier(\id), \Tcolon, \Nty, \Tarrow, \Nstmtlist)}{\vparsednode})
  \astarrow \\
  \overname{(\langle\id\rangle, \astof{\tty}, \astof{\vstmtlist})}{\vastnode}
  \end{array}
  }
}
\end{mathpar}

\begin{mathpar}
\inferrule[unnamed]{}{
  {
  \begin{array}{r}
  \buildcatcher(\overname{\Ncatcher(\Twhen, \Nty, \Tarrow, \Nstmtlist)}{\vparsednode})
  \astarrow \\
  \overname{(\None, \astof{\tty}, \astof{\vstmtlist})}{\vastnode}
  \end{array}
  }
}
\end{mathpar}

\section{Typing}
\TypingRuleDef{Catcher}
\ProseParagraph
One of the following applies:
\begin{itemize}
  \item All of the following apply (\textsc{none}):
  \begin{itemize}
    \item the catcher has no named identifier, that is, $\vc$ is $(\overname{\None}{\nameopt}, \tty, \vstmt)$;
    \item annotating the type $\tty$ in $\tenv$ yields $(\ttyp, \vsesty)$\ProseOrTypeError;
    \item determining whether $\ttyp$ has the \structure\ of an exception type yields \\ $\True$\ProseOrTypeError;
    \item annotating the block $\vstmt$ in $\tenv$ yields $\newstmt$;
    \item \Proseeqdef{$\newcatcher$}{$(\overname{\None}{\nameopt}, \ttyp, \newstmt)$};
  \end{itemize}

  \item All of the following apply (\textsc{some}):
  \begin{itemize}
    \item the catcher has a named identifier, that is, $\vc$ is $(\langle\name\rangle, \tty, \vstmt)$;
    \item annotating the type $\tty$ in $\tenv$ yields $(\ttyp, \vsesty)$\ProseOrTypeError;
    \item determining whether $\ttyp$ has the \structure\ of an exception type yields \\ $\True$\ProseOrTypeError;
    \item the identifier $\name$ is not bound in $\tenv$;
    \item binding $\name$ in the local environment of $\tenv$ with the type $\ttyp$ as an immutable variable
          (that is, with the local declaration keyword $\LDKLet$), yields the static environment $\tenvp$;
    \item annotating the block $\vstmt$ in $\tenvp$ yields $\newstmt$;
    \item \Proseeqdef{$\newcatcher$}{$(\overname{\langle\name\rangle}{\nameopt}, \ttyp, \newstmt)$};
  \end{itemize}
  \item \Proseeqdef{$\vsesfiltered$}{$\vsesin$ where every \ThrowExceptionTerm\ with an exception $\name$ such that
        $\subtypesrel(\tenv, \TNamed(\name), \ttyp)$ holds removed};
  \item \Proseeqdef{$\vses$}{the union of $\vsesblock$ and $\vsesty$}.
\end{itemize}

\FormallyParagraph
\begin{mathpar}
\inferrule[none]{
  \vc = (\overname{\None}{\nameopt}, \tty, \vstmt)\\
  \annotatetype{\tenv, \vt} \typearrow (\ttyp, \vsesty) \OrTypeError\\\\
  \checkstructurelabel(\tenv, \ttyp, \TException) \typearrow \True \OrTypeError\\\\
  \annotateblock{\tenv, \vstmt} \typearrow (\newstmt, \vsesblock) \OrTypeError\\\\
  \newcatcher \eqdef (\overname{\None}{\nameopt}, \ttyp, \newstmt)\\\\
  \commonsuffixline\\\\
  {
    \begin{array}{rl}
  \vsesfiltered \eqdef  & \vsesin \setminus \\
                        & \{ \ThrowException(\name) \;|\; \subtypesrel(\tenv, \TNamed(\name), \ttyp) \}
    \end{array}
  }\\
  \vses \eqdef \vsesblock \cup \vsesty\\
}{
  \annotatecatcher{\tenv, \vsesin, \vc} \typearrow (\vsesfiltered, \newcatcher, \vses)
}
\end{mathpar}
\CodeSubsection{\CatcherNoneBegin}{\CatcherNoneEnd}{../Typing.ml}
\lrmcomment{This is related to \identr{SDJK}.}

\begin{mathpar}
\inferrule[some]{
  \vc = (\overname{\langle\name\rangle}{\nameopt}, \tty, \vstmt)\\
  \annotatetype{\tenv, \vt} \typearrow (\ttyp, \vsesty) \OrTypeError\\\\
  \checkstructurelabel(\tenv, \ttyp, \TException) \typearrow \True \OrTypeError\\\\
  \checkvarnotinenv{\tenv, \name} \typearrow \True \OrTypeError\\\\
  \addlocal(\tenv, \name, \ttyp, \LDKLet) \typearrow \tenvp\\
  \annotateblock{\tenvp, \vstmt} \typearrow (\newstmt, \vsesblock) \OrTypeError\\\\
  \newcatcher \eqdef (\overname{\langle\name\rangle}{\nameopt}, \ttyp, \newstmt)\\\\
  \commonsuffixline\\\\
  {
    \begin{array}{rl}
  \vsesfiltered \eqdef  & \vsesin \setminus \\
                        & \{ \ThrowException(\name) \;|\; \subtypesrel(\tenv, \TNamed(\name), \ttyp) \}
    \end{array}
  }\\
  \vses \eqdef \vsesblock \cup \vsesty\\
}{
  \annotatecatcher{\tenv, \vsesin, \vc} \typearrow (\vsesfiltered, \newcatcher, \vses)
}
\end{mathpar}
% and ses_filtered =
% let ty_name = match ty'.desc with T_Named s -> s | _ -> assert false in
% SES.filter_thrown_exceptions
%   (fun s -> not (Types.subtypes_names env s ty_name))
%   ses_in
% in
% let ses = SES.union ses_block ses_ty in

\CodeSubsection{\CatcherBegin}{\CatcherEnd}{../Typing.ml}
\lrmcomment{This is related to \identr{SDJK}, \identr{WVXS}, \identi{FCGK}.}

\section{Semantics}
\SemanticsRuleDef{Catch}
\subsubsection{Example}
The specification in \listingref{semantics-catch} terminates successfully.
That is, no dynamic error occurs.
\ASLListing{Catching an exception}{semantics-catch}{\semanticstests/SemanticsRule.Catch.asl}

\ProseParagraph
All of the following apply:
\begin{itemize}
  \item $\sm$ is $\Throwing((\langle \valuereadfrom(\vv, \eid), \vvty \rangle, \sg), \envthrow)$;
  \item $\env$ consists of the static environment $\tenv$ and dynamic environment $\denv$;
  \item $\envthrow$ consists of the static environment $\tenv$ and dynamic environment \\ $\denvthrow$;
  \item finding the first catcher with the static environment $\tenv$, the exception type $\vvty$,
  and the list of catchers $\catchers$ gives a catcher that does not declare a name ($\None$) and gives a statement $\vs$;
  \item evaluating $\vs$ in $\envthrow$ as a block (\SemanticsRuleRef{Block}) yields a (non-error)
        configuration $C$\ProseOrError;
  \item editing potential implicit throwing configurations via $\rethrowimplicit(\vv, \vvty, C)$
        gives the configuration $D$;
  \item $\newg$ is the ordered composition of $\sg$ and the graph of $D$;
  \item the result of the entire evaluation is $D$ with its graph substituted with $\newg$.
\end{itemize}

\FormallyParagraph
\begin{mathpar}
\inferrule{
  \sm \eqname \Throwing((\langle \valuereadfrom(\vv, \eid), \vvty \rangle, \sg), \envthrow)\\
  \env \eqname (\tenv, (G^\denv, L^\denv))\\
  \envthrow \eqname (\tenv, (G^{\denvthrow}, L^{\denvthrow}))\\
  \findcatcher(\tenv, \vvty, \catchers) \eqname \langle (\None, \Ignore, \vs) \rangle\\
  \evalblock{\envthrow, \vs} \evalarrow C \OrDynError\\\\
  D \eqdef \rethrowimplicit(\vv, \vvty, C)\\
  \newg \eqdef \ordered{\sg}{\aslpo}{\graphof{D}}
}{
  \evalcatchers{\env, \catchers, \otherwiseopt, \sm} \evalarrow \withgraph{D}{\newg}
}
\end{mathpar}
\CodeSubsection{\EvalCatchBegin}{\EvalCatchEnd}{../Interpreter.ml}

\SemanticsRuleDef{CatchNamed}
\subsubsection{Example}
The specification in \listingref{semantics-catchnamed}, prints \texttt{My exception with my message}.
\ASLListing{Catching a named exception}{semantics-catchnamed}{\semanticstests/SemanticsRule.CatchNamed.asl}

\ProseParagraph
All of the following apply:
\begin{itemize}
  \item $\sm$ is $\Throwing((\langle \valuereadfrom(\vv, \eid), \vvty \rangle, \sg), \envthrow)$;
  \item $\env$ consists of the static environment $\tenv$ and dynamic environment $\denv$;
  \item $\envthrow$ consists of the static environment $\tenv$ and dynamic environment \\ $\denvthrow$;
  \item finding the first catcher with the static environment $\tenv$, the exception type $\vvty$,
  and the list of catchers $\catchers$ gives a catcher that declares the name $\name$ and gives a statement $\vs$;
  \item $\vgone$ is the execution graph resulting from reading $\vv$ into the identifier $\eid$;
  \item declaring a local identifier $\name$ with $(\veone, \vgone)$ in $\envthrow$ gives $(\envtwo, \vgtwo)$;
  \item evaluating $\vs$ in $\envtwo$ as a block (\SemanticsRuleRef{Block}) is not an error
  configuration $C$\ProseOrError;
  \item $\envthree$ is the environment of the configuration $C$;
  \item removing the binding for $\name$ from the local component of the dynamic environment in $\envthree$
  gives $\envfour$;
  \item substituting the environment of $C$ with $\envfour$ gives $D$;
  \item editing potential implicit throwing configurations via $\rethrowimplicit(\vv, \vvty, D)$
  gives the configuration $E$;
  \item $\newg$ is the ordered composition of $\sg$, $\vgone$, $\vgtwo$, and the graph of $E$,
  with the $\aslpo$ edges;
  \item the result of the entire evaluation is $E$ with its graph substituted with $\newg$.
\end{itemize}
\FormallyParagraph
\begin{mathpar}
\inferrule{
  \sm \eqname \Throwing((\langle \valuereadfrom(\vv, \eid), \vvty \rangle, \sg), \envthrow)\\
  \env \eqname (\tenv, (G^\denv, L^\denv))\\
  \envthrow \eqname (\tenv, (G^{\denvthrow}, L^{\denvthrow}))\\
  \findcatcher(\tenv, \vvty, \catchers) \eqname \langle (\langle\name\rangle, \Ignore, \vs) \rangle\\
  \vgone \eqdef \readidentifier(\eid, \vv)\\
  \declarelocalidentifierm(\envthrow, \name, (\veone, \vgone)) \evalarrow (\envtwo, \vgtwo)\\
  \evalblock{\envtwo, \vs} \evalarrow C \OrDynError\\\\
  \envthree \eqdef \environof{C}\\
  \removelocal(\envthree, \name) \evalarrow \envfour\\
  D \eqdef \withenviron{C}{\envfour}\\
  E \eqdef \rethrowimplicit(\vv, \vvty, D)\\
  \newg \eqdef \ordered{\sg}{\aslpo}{ \ordered{\ordered{\vgone}{\aslpo}{\vgtwo}}{\aslpo}{\graphof{E}} }
}{
  \evalcatchers{\env, \catchers, \otherwiseopt, \sm} \evalarrow \withgraph{E}{\newg}
}
\end{mathpar}
\CodeSubsection{\EvalCatchNamedBegin}{\EvalCatchNamedEnd}{../Interpreter.ml}

\SemanticsRuleDef{CatchOtherwise}
\subsubsection{Example}
The specification in \listingref{semantics-catchotherwise} prints \texttt{Otherwise}.
\ASLListing{Catching an exception with \texttt{otherwise}}{semantics-catchotherwise}{\semanticstests/SemanticsRule.CatchOtherwise.asl}

\ProseParagraph
All of the following apply:
\begin{itemize}
  \item $\sm$ is $\Throwing((\langle \valuereadfrom(\vv, \eid), \vvty \rangle, \sg), \envthrow)$;
  \item $\env$ consists of the static environment $\tenv$ and dynamic environment $\denv$;
  \item $\envthrow$ consists of the static environment $\tenv$ and dynamic environment \\ $\denvthrow$;
  \item finding the first catcher with the static environment $\tenv$, the exception type $\vvty$,
  and the list of catchers $\catchers$ gives a catcher that declares the name $\name$ and gives $\None$
  (that is, neither of the \texttt{catch} clauses matches the raised exception);
  \item evaluating the \texttt{otherwise} statement $\vs$ in $\envtwo$ as a block (\SemanticsRuleRef{Block})
  is not an error configuration $C$\ProseOrError;
  \item editing potential implicit throwing configurations via $\rethrowimplicit(\vv, \vvty, C)$
  gives the configuration $D$;
  \item $\newg$ is the ordered composition of $\sg$ and the graph of $D$,
  with the $\aslpo$ edge;
  \item the result of the entire evaluation is $D$ with its graph substituted with $\newg$.
\end{itemize}

\FormallyParagraph
\begin{mathpar}
\inferrule{
  \sm \eqname \Throwing((\langle \valuereadfrom(\vv, \eid), \vvty \rangle, \sg), \envthrow)\\
  \env \eqname (\tenv, (G^\denv, L^\denv))\\
  \envthrow \eqname (\tenv, (G^{\denvthrow}, L^{\denvthrow}))\\
  \findcatcher(\tenv, \vvty, \catchers) = \None\\
  \evalblock{\envthrow, \vs} \evalarrow C \OrDynError\\\\
  D \eqdef \rethrowimplicit(\vv, \vvty, C)\\
  \vg \eqdef \ordered{\sg}{\aslpo}{\graphof{D}}
}{
  \evalcatchers{\env, \catchers, \langle\vs\rangle, \sm} \evalarrow \withgraph{D}{\vg}
}
\end{mathpar}
\CodeSubsection{\EvalCatchOtherwiseBegin}{\EvalCatchOtherwiseEnd}{../Interpreter.ml}

\SemanticsRuleDef{CatchNone}
\subsubsection{Example}
The specification in \listingref{semantics-catchnone} does not print anything.
It shows how a \texttt{try} statement (the inner one) may not have a \texttt{catch} clause
that matches the exception type (\texttt{MyExceptionType1}).
\ASLListing{A catch clause that does not match a thrown exception type}{semantics-catchnone}{\semanticstests/SemanticsRule.CatchNone.asl}

\ProseParagraph
All of the following apply:
\begin{itemize}
  \item $\sm$ is $\Throwing((\langle \valuereadfrom(\vv, \eid), \vvty \rangle, \sg), \envthrow)$;
  \item $\env$ consists of the static environment $\tenv$ and dynamic environment $\denv$;
  \item $\envthrow$ consists of the static environment $\tenv$ and dynamic environment \\ $\denvthrow$;
  \item finding the first catcher with the static environment $\tenv$, the exception type $\vvty$,
  and the list of catchers $\catchers$ gives a catcher that declares the name $\name$ and gives $\None$
  (that is, neither of the \texttt{catch} clauses matches the raised exception);
  \item since there no \texttt{otherwise} clause, the result is $\sm$.
\end{itemize}
\FormallyParagraph
\begin{mathpar}
\inferrule{
  \sm \eqname \Throwing((\langle \valuereadfrom(\vv, \eid), \vvty \rangle, \sg), \envthrow)\\
  \env \eqname (\tenv, \denv)\\
  \findcatcher(\tenv, \vvty, \catchers) = \None
}{
  \evalcatchers{\env, \catchers, \None, \sm} \evalarrow \sm
}
\end{mathpar}
\CodeSubsection{\EvalCatchNoneBegin}{\EvalCatchNoneEnd}{../Interpreter.ml}

\SemanticsRuleDef{CatchNoThrow}
\subsubsection{Example}
The specification in \listingref{semantics-nothrow} prints \texttt{No exception raised}.
\ASLListing{A \texttt{try} statement that does not raise an exception}{semantics-nothrow}{\semanticstests/SemanticsRule.CatchNoThrow.asl}

\ProseParagraph
all of the following apply:
\begin{itemize}
  \item One of the following holds:
  \begin{itemize}
    \item (\textsc{implicit\_throw}) $\sm$ is $\Throwing((\None, \sg), \envthrow)$ (that is, an implicit throw);
    \item (\textsc{non\_throwing}) $\sm$ is a normal configuration (that is, the domain of $\sm$ is $\Normal$);
  \end{itemize}
  \item the result is $\sm$.
\end{itemize}

\FormallyParagraph
\begin{mathpar}
\inferrule[implicit\_throw]{
  \sm \eqname \Throwing((\None, \sg), \envthrow)
}{
  \evalcatchers{\env, \catchers, \Ignore, \sm} \evalarrow \sm
}
\end{mathpar}

\begin{mathpar}
\inferrule[non\_throwing]{
  \configdomain{\sm} = \Normal
}{
  \evalcatchers{\env, \catchers, \Ignore, \sm} \evalarrow \sm
}
\end{mathpar}
\CodeSubsection{\EvalCatchNoThrowBegin}{\EvalCatchNoThrowEnd}{../Interpreter.ml}

\SemanticsRuleDef{FindCatcher}
\hypertarget{def-findcatcher}{}
The (recursively-defined) helper relation
\[
  \findcatcher(\overname{\staticenvs}{\tenv} \aslsep \overname{\ty}{\vvty}, \overname{\catcher^*}{\catchers})
  \;\aslrel\; \langle \catcher \rangle \enspace,
\]
returns the first catcher clause in $\catchers$ that matches the type $\vvty$ (as a singleton set), or an empty set ($\None$),
by invoking $\typesat$ with the static environment $\tenv$.

\ProseParagraph
One of the following applies:
\begin{itemize}
  \item All of the following apply (\textsc{empty}):
  \begin{itemize}
    \item $\catchers$ is an empty list;
    \item the result is $\None$.
  \end{itemize}

  \item All of the following apply (\textsc{match}):
  \begin{itemize}
    \item $\catchers$ has $\vc$ as its head and $\catchersone$ as its tail;
    \item $\vc$ consists of $(\nameopt, \ety, \vs)$;
    \item $\vvty$ \subtypesterm\ $\ety$ in the static environment $\tenv$;
    \item the result is the singleton set for $\vc$.
  \end{itemize}

  \item All of the following apply (\textsc{no\_match}):
  \begin{itemize}
    \item $\catchers$ has $\vc$ as its head and $\catchersone$ as its tail;
    \item $\vc$ consists of $(\nameopt, \ety, \vs)$;
    \item $\vvty$ does not \subtypeterm\ $\ety$ in the static environment $\tenv$;
    \item the result of finding a catcher for $\vvty$ with the type environment $\tenv$ in the tail list $\catchersone$
    is $d$;
    \item the result is $d$.
  \end{itemize}
\end{itemize}

\FormallyParagraph
\begin{mathpar}
\inferrule[empty]{}{\findcatcher(\tenv, \vvty, \emptylist) \evalarrow \None}
\end{mathpar}

\begin{mathpar}
\inferrule[match]{
  \catchers \eqname [\vc] \concat \catchersone\\
  \vc \eqname (\nameopt, \ety, \vs) \\
  \subtypes(\tenv, \vvty, \ety)
}{
  \findcatcher(\tenv, \vvty, \catchers) \evalarrow \langle\vc\rangle
}
\end{mathpar}

\begin{mathpar}
\inferrule[no\_match]{
  \catchers \eqname [\vc] \concat \catchersone\\
  \vc \eqname (\nameopt, \ety, \vs) \\
  \neg\subtypes(\tenv, \vvty, \ety)\\
  d \eqdef \findcatcher(\tenv, \vvty, \catchersone)
}{
  \findcatcher(\tenv, \vvty, \catchers) \evalarrow d
}
\end{mathpar}
\CodeSubsection{\EvalFindCatcherBegin}{\EvalFindCatcherEnd}{../Interpreter.ml}

\subsubsection{Comments}
\lrmcomment{This is related to \identr{SPNM}:}
When the \texttt{catch} of a \texttt{try} statement is executed, then the
thrown exception is caught by the first catcher in that \texttt{catch} which it
type-satisfies or the \texttt{otherwise\_opt} in that catch if it exists.

\SemanticsRuleDef{RethrowImplicit}

The helper relation
\hypertarget{def-rethrowimplicit}{}
\[
  \rethrowimplicit(\overname{\valuereadfrom(\vals,\Identifiers)}{\vv} \aslsep \overname{\ty}{\vvty} \aslsep \overname{\TOutConfig}{\vres}) \;\aslrel\; \TOutConfig
\]

changes \emph{implicit throwing configurations} into \emph{explicit throwing configurations}.
That is, configurations of the form $\Throwing((\None, \vg), \envthrowone))$.

$\rethrowimplicit$ leaves non-throwing configurations, and \emph{explicit throwing configurations},
which have the form $\Throwing(\langle(\valuereadfrom(\vv', \eid), \vvty')\rangle, \vg)$, as is.
Implicit throwing configurations are changed by substituting the optional $\valuereadfrom$ configuration-exception type
pair with $\vv$ and $\vvty$, respectively.

\ProseParagraph
One of the following applies:
\begin{itemize}
  \item All of the following apply (\textsc{implicit\_throwing}):
  \begin{itemize}
    \item $\vres$ is $\Throwing((\None, \vg), \envthrowone)$, which is an implicit throwing configuration;
    \item the result is $\Throwing((\langle(\vv, \vvty)\rangle, \vg), \envthrowone)$.
  \end{itemize}

  \item All of the following apply (\textsc{explicit\_throwing}):
  \begin{itemize}
    \item $\vres$ is $\Throwing(\langle(\vv', \vvty')\rangle, \vg)$, which is an explicit throwing configuration
    (due to $(\vv', \vvty')$);
    \item the result is $\Throwing((\langle(\vv', \vvty')\rangle, \vg), \envthrowone)$. \\
    That is, the same throwing configuration is returned.
  \end{itemize}

  \item All of the following apply (\textsc{non\_throwing}):
  \begin{itemize}
    \item the configuration, $C$, domain is non-throwing;
    \item the result is $C$.
  \end{itemize}
\end{itemize}
\FormallyParagraph
\begin{mathpar}
\inferrule[implicit\_throwing]{}
{
  \rethrowimplicit(\vv, \vvty, \Throwing((\None, \vg), \envthrowone)) \evalarrow \\
  \Throwing((\langle(\valuereadfrom(\vv, \eid), \vvty)\rangle, \vg), \envthrowone)
}
\end{mathpar}

\begin{mathpar}
\inferrule[explicit\_throwing]{}
{
  \rethrowimplicit(\vv, \vvty, \Throwing((\langle(\vv', \vvty')\rangle, \vg), \envthrowone)) \evalarrow \\
  \Throwing((\langle(\vv', \vvty')\rangle, \vg), \envthrowone)
}
\end{mathpar}

\begin{mathpar}
\inferrule[non\_throwing]{
  \configdomain{C} \neq \Throwing
}{
  \rethrowimplicit(\Ignore, \Ignore, C, \Ignore) \evalarrow C
}
\end{mathpar}
\CodeSubsection{\EvalRethrowImplicitBegin}{\EvalRethrowImplicitEnd}{../Interpreter.ml}

\subsubsection{Comments}
\lrmcomment{This is related to \identr{GVKS}:}
An expressionless \texttt{throw} statement causes the exception which the
currently executing catcher caught to be thrown.
